In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
data = pd.read_csv('/content/drive/MyDrive/Machine_Learning_Projects/Project1_BackOrders/BackOrders.csv')
print(data.shape)
print(data.columns)

(61589, 23)
Index(['sku', 'national_inv', 'lead_time', 'in_transit_qty',
       'forecast_3_month', 'forecast_6_month', 'forecast_9_month',
       'sales_1_month', 'sales_3_month', 'sales_6_month', 'sales_9_month',
       'min_bank', 'potential_issue', 'pieces_past_due', 'perf_6_month_avg',
       'perf_12_month_avg', 'local_bo_qty', 'deck_risk', 'oe_constraint',
       'ppap_risk', 'stop_auto_buy', 'rev_stop', 'went_on_backorder'],
      dtype='object')


In [ ]:
data.head()

sku  national_inv  lead_time  in_transit_qty  forecast_3_month  \
0  1888279           117        NaN               0                 0   
1  1870557             7        2.0               0                 0   
2  1475481           258       15.0              10                10   
3  1758220            46        2.0               0                 0   
4  1360312             2        2.0               0                 4   

   forecast_6_month  forecast_9_month  sales_1_month  sales_3_month  \
0                 0                 0              0              0   
1                 0                 0              0              0   
2                77               184             46            132   
3                 0                 0              1              2   
4                 6                10              2              2   

   sales_6_month  ...  pieces_past_due  perf_6_month_avg perf_12_month_avg  \
0             15  ...                0            -99.00            -99.00   
1              0  ...                0              0.50              0.28   
2            256  ...                0              0.54              0.70   
3              6  ...                0              0.75              0.90   
4              5  ...                0              0.97              0.92   

   local_bo_qty  deck_risk  oe_constraint  ppap_risk stop_auto_buy rev_stop  \
0             0         No             No        Yes           Yes       No   
1             0        Yes             No         No           Yes       No   
2             0         No             No         No           Yes       No   
3             0        Yes             No         No           Yes       No   
4             0         No             No         No           Yes       No   

  went_on_backorder  
0                No  
1                No  
2                No  
3                No  
4                No  

[5 rows x 23 columns]

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61589 entries, 0 to 61588
Data columns (total 23 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sku                61589 non-null  int64  
 1   national_inv       61589 non-null  int64  
 2   lead_time          58186 non-null  float64
 3   in_transit_qty     61589 non-null  int64  
 4   forecast_3_month   61589 non-null  int64  
 5   forecast_6_month   61589 non-null  int64  
 6   forecast_9_month   61589 non-null  int64  
 7   sales_1_month      61589 non-null  int64  
 8   sales_3_month      61589 non-null  int64  
 9   sales_6_month      61589 non-null  int64  
 10  sales_9_month      61589 non-null  int64  
 11  min_bank           61589 non-null  int64  
 12  potential_issue    61589 non-null  object 
 13  pieces_past_due    61589 non-null  int64  
 14  perf_6_month_avg   61589 non-null  float64
 15  perf_12_month_avg  61589 non-null  float64
 16  local_bo_qty       615

In [ ]:
cat_features = ['potential_issue', 'deck_risk', 'oe_constraint', 'ppap_risk', 'stop_auto_buy', 'rev_stop', 'went_on_backorder']
data_encoded = pd.get_dummies(data, columns = cat_features, drop_first=True)
data_encoded.shape

(61589, 23)

In [ ]:
data_encoded.columns

Index(['sku', 'national_inv', 'lead_time', 'in_transit_qty',
       'forecast_3_month', 'forecast_6_month', 'forecast_9_month',
       'sales_1_month', 'sales_3_month', 'sales_6_month', 'sales_9_month',
       'min_bank', 'pieces_past_due', 'perf_6_month_avg', 'perf_12_month_avg',
       'local_bo_qty', 'potential_issue_Yes', 'deck_risk_Yes',
       'oe_constraint_Yes', 'ppap_risk_Yes', 'stop_auto_buy_Yes',
       'rev_stop_Yes', 'went_on_backorder_Yes'],
      dtype='object')

In [ ]:
data_encoded.isnull().sum()

sku                         0
national_inv                0
lead_time                3403
in_transit_qty              0
forecast_3_month            0
forecast_6_month            0
forecast_9_month            0
sales_1_month               0
sales_3_month               0
sales_6_month               0
sales_9_month               0
min_bank                    0
pieces_past_due             0
perf_6_month_avg            0
perf_12_month_avg           0
local_bo_qty                0
potential_issue_Yes         0
deck_risk_Yes               0
oe_constraint_Yes           0
ppap_risk_Yes               0
stop_auto_buy_Yes           0
rev_stop_Yes                0
went_on_backorder_Yes       0
dtype: int64

In [ ]:
data_encoded.lead_time.value_counts()

8.0     25116
2.0     13314
12.0     7007
4.0      4372
9.0      4281
52.0      870
3.0       675
0.0       498
10.0      476
14.0      350
16.0      326
6.0       203
13.0      199
5.0       158
15.0      141
17.0      113
11.0       43
20.0       15
30.0        9
18.0        4
7.0         4
22.0        4
24.0        2
26.0        2
1.0         1
40.0        1
35.0        1
28.0        1
Name: lead_time, dtype: int64

In [ ]:
data_encoded['lead_time'].fillna(data_encoded['lead_time'].mean(), inplace = True)

In [ ]:
X = data_encoded.drop(columns = ['went_on_backorder_Yes'])
y = data_encoded['went_on_backorder_Yes']

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    test_size = 0.2,
                                                    random_state = 2,
                                                    stratify = y)

## Decision Tree Classifier

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(class_weight = 'balanced')
dt.fit(X_train, y_train)
y_pred = dt.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_pred, y_test))
print(confusion_matrix(y_pred, y_test))

              precision    recall  f1-score   support

           0       0.94      0.94      0.94     10039
           1       0.74      0.73      0.73      2279

    accuracy                           0.90     12318
   macro avg       0.84      0.83      0.84     12318
weighted avg       0.90      0.90      0.90     12318

[[9441  598]
 [ 618 1661]]


In [ ]:
import numpy as np
importances = dt.feature_importances_

# Sort the importances in descending order
indices = np.argsort(importances)[::-1]

# Print the feature ranking
print("Feature ranking:")
for i, index in enumerate(indices):
    print(f"{i+1}. Feature {index}: {importances[index] * 100}")

Feature ranking:
1. Feature 4: 33.61647268511139
2. Feature 1: 22.10184786394799
3. Feature 0: 8.401508738410891
4. Feature 7: 4.554314417847978
5. Feature 14: 3.990920590524717
6. Feature 13: 3.568035053138811
7. Feature 8: 3.251823219950936
8. Feature 6: 3.223997521621142
9. Feature 9: 3.0725258714677914
10. Feature 10: 2.9790692408997166
11. Feature 2: 2.8344784657507045
12. Feature 3: 2.140668955746057
13. Feature 5: 1.7023099726209148
14. Feature 11: 1.5816326011558774
15. Feature 12: 1.2109510809026676
16. Feature 19: 0.6089925682098344
17. Feature 17: 0.516171598221212
18. Feature 15: 0.36095248402736124
19. Feature 20: 0.25236675107740053
20. Feature 21: 0.022137896634922587
21. Feature 16: 0.008822422731675768
22. Feature 18: 0.0


##Logistic Regression 

In [ ]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(class_weight = 'balanced', penalty = 'none')
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)

print(classification_report(y_pred, y_test))
print(confusion_matrix(y_pred, y_test))

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:1173: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(


              precision    recall  f1-score   support

           0       0.99      0.85      0.91     11735
           1       0.21      0.80      0.33       583

    accuracy                           0.84     12318
   macro avg       0.60      0.82      0.62     12318
weighted avg       0.95      0.84      0.88     12318

[[9940 1795]
 [ 119  464]]


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [12]:
from sklearn.metrics import classification_report, confusion_matrix

def evaluation(y_train_pred, y_test_pred, y_train, y_test):
  print("train_evaluation:\n")
  print(classification_report(y_train_pred, y_train))
  print(confusion_matrix(y_train_pred, y_train))
  print("\ntest_evaluation:\n")
  print(classification_report(y_test_pred, y_test))
  print(confusion_matrix(y_test_pred, y_test))

##Random Forest Classifier

In [13]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

rfc=RandomForestClassifier()

In [15]:
param_grid = {
    # 'max_depth': [3, 5, 7],                     # Maximum depth of the tree
    'min_samples_split': [2, 5, 10],            # Minimum number of samples required to split a node
    # 'min_samples_leaf': [1, 2, 3],              # Minimum number of samples required at a leaf node
    'max_features': ['auto', 'sqrt'],    # Number of features to consider at each split
    'criterion': ['gini', 'entropy', 'log_loss'],
    # 'oob_score': [True, False],
    'class_weight': ['balanced', 'balanced_subsample']
}

# Perform grid search to find the best combination of parameters
grid_search = GridSearchCV(rfc, param_grid, cv=5)
grid_search.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_forest.py:424: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_forest.py:424: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_forest.py:424: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomFor

GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'class_weight': ['balanced', 'balanced_subsample'],
                         'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_features': ['auto', 'sqrt'],
                         'min_samples_split': [2, 5, 10]})

In [16]:
print("Best Parameters: ", grid_search.best_params_)
print("Best Score: ", grid_search.best_score_)

Best Parameters:  {'class_weight': 'balanced', 'criterion': 'entropy', 'max_features': 'auto', 'min_samples_split': 2}
Best Score:  0.9335714995504636


In [17]:
y_test_pred = grid_search.predict(X_test)
y_train_pred = grid_search.predict(X_train)
evaluation(y_train_pred, y_test_pred, y_train, y_test)

train_evaluation:

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     40237
           1       1.00      1.00      1.00      9034

    accuracy                           1.00     49271
   macro avg       1.00      1.00      1.00     49271
weighted avg       1.00      1.00      1.00     49271

[[40237     0]
 [    0  9034]]

test_evaluation:

              precision    recall  f1-score   support

           0       0.97      0.96      0.96     10166
           1       0.80      0.84      0.82      2152

    accuracy                           0.94     12318
   macro avg       0.88      0.90      0.89     12318
weighted avg       0.94      0.94      0.94     12318

[[9713  453]
 [ 346 1806]]


In [26]:
rf = RandomForestClassifier(n_estimators = 120, class_weight = 'balanced', criterion = 'entropy')
rf.fit(X_train, y_train)
y_test_pred = rf.predict(X_test)
y_train_pred = rf.predict(X_train)
evaluation(y_train_pred, y_test_pred, y_train, y_test)

train_evaluation:

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     40237
           1       1.00      1.00      1.00      9034

    accuracy                           1.00     49271
   macro avg       1.00      1.00      1.00     49271
weighted avg       1.00      1.00      1.00     49271

[[40237     0]
 [    0  9034]]

test_evaluation:

              precision    recall  f1-score   support

           0       0.97      0.96      0.96     10152
           1       0.80      0.84      0.82      2166

    accuracy                           0.94     12318
   macro avg       0.88      0.90      0.89     12318
weighted avg       0.94      0.94      0.94     12318

[[9707  445]
 [ 352 1814]]
